build_mode = "release"
target_adapters = ["circom"]
target_platforms = [
    "ios",
    "android",
]
ios = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
]
android = [
    "x86_64-linux-android",
    "aarch64-linux-android",
]
